data:
  coils: 16
  dataset_key: ktspace
  eval_timeframes: 22
  height: 320
  root_dir: /ess/scratch/scratch1/rachelgordon/dce-8tf/binned_kspace
  split_file: /gpfs/data/karczmar-lab/workspaces/rachelgordon/breastMRI-recon/ddei/data/data_split.json
  spokes_per_frame: 640
  timeframes: 8
  total_spokes: 288
  val_split_ratio: 0.2
  width: 320
dataloader:
  batch_size: 1
  max_subjects: 300
  num_workers: 2
  shuffle: false
  slice_idx: 41
debugging:
  calc_step_0: true
  enable_gradient_monitoring: true
  monitoring_interval: 5
evaluation:
  num_samples: 15
  simulated_dataset_path: /ess/scratch/scratch1/rachelgordon/simulated_dataset/
experiment:
  output_dir: output
model:
  cascades: 2
  channels: 16
  gamma: 0.5
  lambda_L: 0.05
  lambda_S: 0.05
  lambda_spatial_L: 0.05
  lambda_spatial_S: 0.05
  lambda_step: 0.1
  losses:
    adj_loss:
      weight: 0.0001
    ei_loss:
      duration: 5
      subsample_ratio_max: 0.95
      subsample_ratio_min: 0.7
      temporal_transform: subsample
      warmup: 3
      warp_ratio_max: 0.95
      warp_ratio_min: 0.6
      weight: 0
    mc_loss:
      weight: 10
    use_ei_loss: false
  name: LSFPNet
  norm: both
  num_layers: 3
  optimizer:
    b1: 0.9
    b2: 0.999
    eps: 1.0e-09
    lr: 0.0005
    name: Adam
    weight_decay: 0.0
training:
  device: cuda
  epochs: 10
  plot_interval: 20
  save_interval: 1
