# Directories for input data
data:
  root_dir: "/ess/scratch/scratch1/rachelgordon/dce-8tf/binned_kspace"
  dataset_key: "ktspace"
  split_file: "/gpfs/data/karczmar-lab/workspaces/rachelgordon/breastMRI-recon/ddei/patient_splits.json"
  val_split_ratio: 0.2
  height: 320
  width: 320
  timeframes: 8
  total_spokes: 288
  spokes_per_frame: 640
  coils: 16

# Experiment settings
experiment:
  output_dir: "output"

# DataLoader settings
dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 2
  max_subjects: 100
  slice_idx: 41

# Model settings
model:
  name: "LSFPNet"
  num_layers: 8
  cascades: 2
  channels: 8
  optimizer:
    name: "Adam"
    lr: 0.0001
    weight_decay: 0.0
    b1: 0.9
    b2: 0.999
    eps: 0.000000001
  scheduler:
      enable: true
      type: "cosine"
      min_lr: 1.0e-6
  losses:
    use_ei_loss: true
    mc_loss:
      weight: 10
    ei_loss:
      temporal_transform: "subsample"
      weight: 100 #0.0003
      warmup: 5
      duration: 100
      subsample_ratio_min: 0.7
      subsample_ratio_max: 0.95
      warp_ratio_min: 0.6
      warp_ratio_max: 0.95
    adj_loss:
      weight: 0.0001
  normalization: "kspace"
  two_physics: false


# Training settings
training:
  epochs: 100
  save_interval: 1
  plot_interval: 20
  device: "cuda"  # or "cpu"
evaluation:
  num_samples: 0
  simulated_dataset_path: "/ess/scratch/scratch1/rachelgordon/simulated_dataset/"

debugging:
  calc_step_0: true
  enable_gradient_monitoring: true
  monitoring_interval: 5