# Directories for input data
data:
  root_dir: "/ess/scratch/scratch1/rachelgordon/dce-8tf/binned_kspace"
  dataset_key: "ktspace"
  split_file: "/gpfs/data/karczmar-lab/workspaces/rachelgordon/breastMRI-recon/ddei/patient_splits.json"
  val_split_ratio: 0.2
  height: 320
  width: 320
  timeframes: 8
  total_spokes: 288
  spokes_per_frame: 640
  coils: 1

# Experiment settings
experiment:
  output_dir: "output"

# DataLoader settings
dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 2
  max_subjects: 300
  slice_idx: 41

# Model settings
model:
  name: "DDEI"
  cascades: 2
  channels: 64
  optimizer:
    name: "Adam"
    lr: 0.000005
    weight_decay: 0.0
    b1: 0.9
    b2: 0.999
    eps: 0.000000001
  losses:
    use_ei_loss: true
    mc_loss:
      weight: 1
    ei_loss:
      temporal_transform: "noise"
      weight: 0.0003
      warmup: 3
      duration: 5
      subsample_ratio_min: 0.7
      subsample_ratio_max: 0.95
      warp_ratio_min: 0.6
      warp_ratio_max: 0.95


# Training settings
training:
  epochs: 10
  save_interval: 1
  plot_interval: 20
  device: "cuda"  # or "cpu"